#!/bin/bash

########################  MAIN

_echot "------- install"
packages="bless ghex lnav net-tools pv"
# sysstat
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- aur"
packages="wxhexeditor"
_install_aur ${packages}

_echot "------- conf bless"
pth=${HOME}/.config/bless/layouts/
[ -d "${pth}" ] || mkdir -p ${pth}
cp ${_PATH_BASE}/conf/bless/* ${pth}/
