#!/bin/bash

########################  GLOBAL

_echot "------- install"
packages="geany git gitg openssh lnav pv squashfs-tools jq jre-openjdk"
# gitk 
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- geany"
pth=${HOME}/.config/geany/colorschemes
[ -d "${pth}" ] || mkdir -p ${pth}
cp ${_PATH_BASE}/conf/geany/* ${pth}/

_echot "------- aur"
packages="gtkhash xsysinfo"
_install_aur ${packages}
