#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- install"
packages="geany git gitg gitk gtkhash openssh-server"
packages+=" lnav mkisofs pv squashfs-tools xsysinfo"
packages+=" jre-openjdk"
# sysstat
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- geany"
path=${HOME}/.config/geany/colorschemes
[ -d "${path}" ] || mkdir -p ${path}
cp ${_PATH_BASE}/conf/geany/* ${path}/
