#!/bin/bash

########################  MAIN

if ! which imhex >/dev/null; then
	_echot "------- imhex"
	anstmp=1.37.4-ArchLinux-x86_64
	_echoa "url to see available releases: https://github.com/WerWolv/ImHex/tags"
	_askno "Give the version to download imhex from github (${anstmp})"
	imhex_version=${_ANSWER:-${anstmp}}
	file=imhex-${imhex_version}.pkg.tar.zst
	pth=/tmp/${file}
	if ! [ -f ${pth} ]; then
		url=https://github.com/WerWolv/ImHex/releases/download/v${imhex_version%%-*}/${file}
		_eval wget -qO ${pth} ${url} || _exite "Error while downloading url: ${url}"
	fi

	_echot "------- install"
	_evalr pacman -U --noconfirm ${pth} || _exite "Unable to install ${pth}"
fi
