#!/bin/bash

_echot "------- tools"
packages="dnsutils openbsd-netcat net-tools traceroute whois"
packages+=" bmon darkstat hping iftop tcpdump vnstat"
# vnstat-client
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- aur"
packages="ifstat xinetd"
_install_aur ${packages}
