#!/bin/bash

_echot "------- tools"
packages="dnsutils openbsd-netcat net-tools traceroute whois"
packages+=" bmon darkstat hping iftop tcpdump vnstat"
# vnstat-client
_install_pcks ${packages}

_echot "------- aur"
packages="ifstat xinetd"
_install_aur ${packages}
