#!/bin/bash

_echot "------- tools"
packages="dnsutils gnu-netcat net-tools traceroute whois"
packages+=" bmon darkstat hping iftop tcpdump vnstat"
# vnstat-client
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- aur"
packages="xinetd ifstat"
for package in ${packages}; do
	if ! yay -Qe ${package} >/dev/null 2>&1; then
		_echot "install ${package}"
		${_CMD_AUR} ${package} || _exite "Unable to install: ${package}"
	else
		_echot "already installed ${package}"
	fi
done
