#!/bin/bash

########################  MAIN

_echot "------- install"
packages="cython python-pip"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
