#!/bin/bash

########################  MAIN

_echot "------- install"
packages="cython python python-pip python-pipx"
_install_pcks ${packages}

packages="virtualenv grip"
for package in ${packages}; do
	_echot "------- pipx"
	_eval pipx install ${package}
done
