#!/bin/bash

_echot "------- install"
packages="wireshark-qt termshark"
# wireshark-gtk2
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- wireshark"
_eval cp ${_PATH_BASE}/xtra/org.wireshark.Wireshark.desktop ~/.local/share/applications/
