#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

_echot "------------------ install"
packages="gimp gimp-plugin-gmic gimp-nufraw "
#packages+=" lightzone"
# ijsgutenprint gimp-save-for-web gimp-normal-map gimp-plugin-registry gimp-dbg gimp-ufraw sozi pandora xsane
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ aur"
packages="gimp gimp-extras gimp-fourier gimp-paint-studio gimp-plugin-bimp gimp-plugin-pandora gimp-plugin-refocusit gimp-plugin-resynthesizer-git gimp-plugin-saveforweb"
# wait for good version:  gimp-plugin-beautify gimp-plugin-texturize
for package in ${packages}; do
    if ! yay -Qe ${package} >/dev/null 2>&1; then
        _echot "install ${package}"
        ${_CMD_AUR} ${package} || _exite "Unable to install: ${package}"
    else
        _echot "already installed ${package}"
    fi
done

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
