#!/bin/bash
#
# write by Aguy

_echot "------- libreoffice"
packages="libreoffice-extension-texmaths libreoffice-extension-writer2latex"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
