#!/bin/bash
#
# write by Aguy

_echot "-------  install"
packages="nextcloud-client"
# csync-owncloud
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

########################  END

_partadd "${_PART}" "${_FILE_DONE}"
