#!/bin/bash

_echot "------- python"
packages="python python-pip"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- pip"
packages="pip yt-dlp"
python3 -m pip install -U ${packages} \
	|| { _echoE "Unable to install pip: ${packages}"; return 1; }
