#!/bin/bash

########################  REQUIRED

file_meld_conf=${_PATH_BASE}/conf/soft/meld-perso-dark.style-scheme.xml
_require ${file_meld_conf}

pth_gtk=${_PATH_BASE}/conf/gtk
_requirep ${pth_gtk}

########################  SYSTEM

_echot "------- grub"
file=/etc/default/grub
_keepcp ${file}
sudo sed -i "s|^.\?\(GRUB_TIMEOUT_STYLE\)=.*|\1=menu|" ${file}
sudo sed -i "/^GRUB_TIMEOUT=/ s|=.*|=2|" ${file}
sudo sed -i "/^GRUB_DEFAULT=/ s|=.*|=0|" ${file}
sudo sed -i "/^GRUB_SAVEDEFAULT=/ s|=.*|=false|" ${file} # manjaro
file=/etc/grub.d/00_header
_keepcp ${file}
_evalr chmod -x ${file}.keep
sudo sed -i "s|30|2|g" ${file}
_evalr update-grub

_echot "------- grub os-prober"
# add identifier to menuentry
file=/etc/grub.d/30_os-prober
if ! grep -q 'LONGNAME="${LONGNAME} ${BTRFSsubvol/#subvol=/}"' ${file}; then
	_keepcp ${file} && _evalr chmod -x ${file}.keep
	sudo sed -i "/LONGNAME=\"\${LABEL}\"/ a\  else\n    LONGNAME=\"\${LONGNAME} \${BTRFSsubvol/#subvol=/}\"" ${file}
fi
_echot "------- reduce swapiness"
_evalr swapoff -av
sudo sh -c 'echo vm.swappiness=40 > /etc/sysctl.d/99-swappiness.conf' # limit swap
_evalr swapon -v

_echot "------- profile"
export PATH="${PATH}:${_PATH_BS}"
export QT_QPA_PLATFORMTHEME=qt6ct
sudo sh -c "echo '# PATH
export PATH=\${PATH}:${_PATH_BS}
# QT6
export QT_QPA_PLATFORMTHEME=qt6ct' > /etc/profile.d/desktop.sh"

_echot "------- QT_QPA_PLATFORMTHEME"
export QT_QPA_PLATFORMTHEME=qt6ct
sudo grep 'export QT_QPA_PLATFORMTHEME' /etc -rl|xargs sudo sed -i '/export QT_QPA_PLATFORMTHEME=/ s|=.*$|=qt6ct|'

_echot "------- bash-completion"
_evalr "cp -a ${_PATH_BASE}/xtra/bash-completion/* /usr/share/bash-completion/completions/"

_echot "------- vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------- vim colors"
_evalr cp ${_PATH_BASE}/conf/vim/* /usr/share/vim/vim*/colors/

_echot "------- vim conf"
file=/etc/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------- nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap " # various
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor" # color
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------- meld style"
file=/usr/share/meld/styles/meld-dark.style-scheme.xml
_keepmv ${file}
_evalr cp ${_PATH_BASE}/conf/meld-dark.style-scheme.xml ${file}

_echot "------- icons"
pth=/usr/share/icons/Foralyse
[ -d "${pth}" ] || _evalr mkdir -p ${pth}
_evalr cp ${_PATH_BASE}/icons/* ${pth}/

_echot "------- wp"
pth=/usr/share/backgrounds/xfce
_evalr cp ${_PATH_BASE}/xtra/wp/* ${pth}/
_evalr chmod 644 ${pth}/*

_echot "------- numlockx in tty"
file=/etc/lightdm/lightdm-gtk-greeter.conf
# ally-states
if grep -q "^a11y-states *=" ${file}; then
	sudo sed -i "s|\(^a11y-states.*\)$|\1;+keyboard|" ${file}
else
	sudo sh -c "echo 'a11y-states = +keyboard' >> ${file}"
fi

_echot "------- numlockx in ldm"
file=/etc/lightdm/lightdm-gtk-greeter.conf
cmd="/usr/bin/numlockx on"
# keyboard
if grep -q "^keyboard *=" ${file}; then
	sudo sed -i "s|\(^keyboard *=\)|\1 ${cmd}|" ${file}
else
	sudo sh -c "echo 'keyboard = ${cmd}' >> ${file}"
fi

########################  USER

_echot "------- user icons"
pth=${HOME}/.local/share/icons
_eval cp ${_PATH_BASE}/icons/* ${pth}/

_echot "------- user conf"
for file in .nanorc .tmux.conf .vimrc; do
	pth=${HOME}/${file}
	_keepmv "${pth}"
	_eval ln -s "${_PATH_BS}/conf/${file}" "${pth}"
done

_echot "------- thunar-volman"
_eval xfconf-query -c thunar-volman -n -p /autobrowse/enabled -t bool -s false
_eval xfconf-query -c thunar-volman -n -p /automount-drives/enabled -t bool -s false
_eval xfconf-query -c thunar-volman -n -p /automount-media/enabled -t bool -s false

_echot "------- gtk4"
pth_to="${HOME}/.local/share/gtksourceview-4"
[ -d "${pth_to}" ] && _keepmvts "${pth_to}"
_eval cp -a ${pth_gtk} ${pth_to}

_echot "------- gtk3"
cd "${HOME}/.local/share"
[ -e "gtksourceview-4" ] || _eval ln -s gtksourceview-4 gtksourceview-3.0

_echot "------- user conf"
pths=".tmux"
for pth in ${pths}; do
	_keepmv ${pth}
done
for file in ${_PATH_BASE}/conf/user.tmux.tar.gz; do
	_eval tar xzf ${file} -C ${HOME}/
done

_echot "------- aegisub"
pth=${HOME}/.aegisub/
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_eval cp ${_PATH_BASE}/conf/aegisub-config.json ${pth}

_echot "------- tmux desktop"
_eval cp ${_PATH_BASE}/xtra/xfce4-terminal-tmux.desktop ${HOME}/.local/share/applications/

_echot "------- QT"
_echoA "After validation, adjust settings for qt6 and close qt6ct window"
_askno "Validate to continue"
qt6ct 2>/dev/null

_echot "------- plank"
pth=${HOME}/.config/autostart
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_eval cp ${_PATH_BASE}/xtra/plank.desktop ${pth}/
_echoA "After validation, adjust plank preferences and close plank window"
_askno "Validate to continue"
plank --preferences &
