#!/bin/bash

########################  MAIN

_echot "------- remove"
packages="manjaro-xfce-minimal-settings kvantum-theme-matcha matcha-gtk-theme"
_evalr pacman -R --noconfirm ${packages}

_echot "------- manjaro add"
# removed by predecessor
packages="manjaro-base-skel papirus-maia-icon-theme xcursor-breeze xcape"
_evalr pacman -S --noconfirm ${packages}

_echot "------- system"
packages="base-devel bash-completion cdrtools curl exfatprogs gnupg gparted htop most ncdu multipath-tools numlockx pv testdisk tmux tree vim yay"
packages+=" pigz p7zip zip unzip unrar zstd"
_install_pcks ${packages}

_echot "------- tools"
packages="dconf-editor galculator meld plank qt5ct qt6ct thunderbird termdown"
packages+=" thunar-volman thunar-media-tags-plugin jre-openjdk"
# gtk2fontsel
_install_pcks ${packages}

_echot "------- graphic"
packages="inkscape gimp ristretto"
_install_pcks ${packages}

_echot "------- media"
packages=" cheese mpv obs-studio"
_install_pcks ${packages}

_echot "------- audio"
packages="audacity easytag easyeffects soundconverter sound-juicer"
# yt-dlp
_install_pcks ${packages}

_echot "------- video"
packages="handbrake mkvtoolnix-gui aegisub boost-libs"
# kdenlive
_install_pcks ${packages}

_echot "------- aur"
packages="duff gmusicbrowser simplescreenrecorder"
# qarte radiotray-ng webcamoid
_install_aur ${packages}
