#!/bin/bash

########################  MAIN

_echot "------- system"
packages="base-devel bash-completion cdrtools curl exfatprogs gnupg gparted htop most ncdu multipath-tools numlockx pv testdisk tmux tree vim yay"
packages+=" pigz p7zip zip unzip unrar zstd"
_install_pcks ${packages}

_echot "------- tools"
packages="dconf-editor galculator meld plank qt6ct thunderbird termdown"
packages+=" thunar-volman thunar-media-tags-plugin jre-openjdk"
# gtk2fontsel
_install_pcks ${packages}

_echot "------- graphic"
packages="inkscape gimp ristretto"
_install_pcks ${packages}

_echot "------- media"
packages="vokoscreen mpv obs-studio guvcview"
_install_pcks ${packages}

_echot "------- audio"
packages="audacity easytag easyeffects soundconverter sound-juicer"
# yt-dlp
_install_pcks ${packages}

_echot "------- video"
packages="handbrake mkvtoolnix-gui aegisub boost-libs"
# kdenlive
_install_pcks ${packages}

_echot "------- aur"
packages="duff gmusicbrowser"
# qarte radiotray-ng webcamoid simplescreenrecorder
_install_aur ${packages}
