#!/bin/bash

########################  MAIN

_echot "------- update"
_evalr pacman --noconfirm -Sy

_echot "------- upgrade"
_evalr pacman --noconfirm -Su

_echot "------- clean orphans"
[ "$(pacman -Qdtq)" ] && _evalr pacman --noconfirm -R $(pacman -Qdtq) || true
