#!/bin/bash

########################  MAIN

_echot "------- update"
${_CMD} -Sy

_echot "------- upgrade"
${_CMD} -Su

_echot "------- clean orphans"
[ "$(pacman -Qdtq)" ] && ${_CMD} -R $(pacman -Qdtq) || true
