#!/bin/bash

########################  MAIN

_echot "------- config"
packages="manjaro-zsh-config"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
