#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

# media
packages=" gmusicbrowser qarte" # webcamoid

# desktop
[ "${_DESKTOP}" = xfce  ] && packages+=" radiotray-ng zuki-themes"
[ "${_DESKTOP}" = gnome  ] && packages+=" nautilus-compare"

# yay
for package in ${packages}; do
	if ! yay -Qe ${package} >/dev/null 2>&1; then
		_echot "------------------ install ${package}"
		${_CMD_AUR} ${package} || _exite "Unable to install: ${package}"
	else
		_echot "------------------ already installed ${package}"
	fi
done

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
