#!/bin/bash

_echot "------- aur"
packages="cinelerra-gg"
# cin-appimage cinelerra-cv
for package in ${packages}; do
	if ! yay -Qe ${package} >/dev/null 2>&1; then
		_echot "install ${package}"
		${_CMD_AUR} ${package} &&  _partadd "${package}" ${_FILE_PCK} \
			|| _exite "Unable to install: ${package}"
	else
		_echot "already installed ${package}"
	fi
done
