#!/bin/bash

########################  SYSTEM

_echot "------- grub"
file=/etc/default/grub
_keepcp ${file}
sudo sed -i "s|^.\?\(GRUB_TIMEOUT_STYLE\)=.*|\1=menu|" ${file}
sudo sed -i "/^GRUB_TIMEOUT=/ s|=.*|=2|" ${file}
sudo sed -i "/^GRUB_DEFAULT=/ s|=.*|=0|" ${file}
sudo sed -i "/^GRUB_SAVEDEFAULT=/ s|=.*|=false|" ${file} # manjaro
file=/etc/grub.d/00_header
_keepcp ${file}
sudo sed -i "s|30|2|g" ${file}
_evalr update-grub

_echot "------- grub os-prober"
# add identifier to menuentry
file=/etc/grub.d/30_os-prober
if ! grep -q 'LONGNAME="${LONGNAME} ${BTRFSsubvol/#subvol=/}"' ${file}; then
	_keepcp ${file} && sudo chmod -x ${file}.keep
	sudo sed -i "/LONGNAME=\"\${LABEL}\"/ a\  else\n    LONGNAME=\"\${LONGNAME} \${BTRFSsubvol/#subvol=/}\"" ${file}
fi
_echot "------- reduce swapiness"
sudo swapoff -av
sudo sh -c 'echo vm.swappiness=40 > /etc/sysctl.d/99-swappiness.conf' # limit swap
sudo swapon -v

_echot "------- profile"
export PATH="${PATH}:${_PATH_BS}"
sudo sh -c "echo '# PATH
export PATH=\${PATH}:${_PATH_BS}' > /etc/profile.d/desktop.sh"

_echot "------- QT_QPA_PLATFORMTHEME"
export QT_QPA_PLATFORMTHEME=qt5ct
sudo grep 'export QT_QPA_PLATFORMTHEME' /etc -rl|xargs sudo sed -i '/export QT_QPA_PLATFORMTHEME=/ s|=.*$|=qt5ct|'

_echot "------- bash-completion"
_evalr "cp -a ${_PATH_BASE}/xtra/bash-completion/* /usr/share/bash-completion/completions/"

_echot "------- vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------- vim colors"
_evalr cp ${_PATH_BASE}/conf/vim/* /usr/share/vim/vim*/colors/

_echot "------- vim conf"
file=/etc/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------- meld style"
_evalr cp ${_PATH_BASE}/conf/meld-dark.xml /usr/share/meld/styles/

_echot "------- icons"
path=/usr/share/icons/Foralyse
[ -d "${path}" ] || sudo mkdir -p ${path}
_evalr cp ${_PATH_BASE}/icons/* ${path}/

_echot "------- wp"
path=/usr/share/backgrounds/xfce
_evalr cp ${_PATH_BASE}/xtra/wp/* ${path}/
_evalr chmod 644 ${path}/*

_echot "------- numlockx in tty"
file=/etc/lightdm/lightdm-gtk-greeter.conf
# ally-states
if grep -q "^a11y-states *=" ${file}; then
	sudo sed -i "s|\(^a11y-states.*\)$|\1;+keyboard|" ${file}
else
	sudo sh -c "echo 'a11y-states = +keyboard' >> ${file}"
fi

_echot "------- numlockx in ldm"
file=/etc/lightdm/lightdm-gtk-greeter.conf
cmd="/usr/bin/numlockx on"
# keyboard
if grep -q "^keyboard *=" ${file}; then
	sudo sed -i "s|\(^keyboard *=\)|\1 ${cmd}|" ${file}
else
	sudo sh -c "echo 'keyboard = ${cmd}' >> ${file}"
fi

########################  USER

_echot "------- user icons"
path=${HOME}/.local/share/icons
_eval cp ${_PATH_BASE}/icons/* ${path}/

_echot "------- user conf"
for file in .nanorc .tmux.conf .vimrc; do
	path=${HOME}/${file}
	_keepmv "${path}"
	_eval ln -s "${_PATH_BS}/conf/${file}" "${path}"
done

_echot "------- thunar-volman"
xfconf-query -c thunar-volman -p /autobrowse/enabled -s false
xfconf-query -c thunar-volman -p /automount-drives/enabled -s false
xfconf-query -c thunar-volman -p /automount-media/enabled -s false

_echot "------- gtk styles"
path=${HOME}/.local/share/gtksourceview-3.0/styles
# link or copy
path_repo=/home/shared/.local/share/gtksourceview-3.0/styles
if [ -d "${path_repo}" ]; then
	[ -d "${path}" ] && rm -fR ${path}
	ln -sv "${path_repo}" ${path}
else
	[ -d "${path}" ] || mkdir -p ${path}
	_eval cp ${_PATH_BASE}/conf/styles/* ${path}/
fi
# gtk 4
cd ${HOME}/.local/share
path=gtksourceview-4
[ -e "${path}" ] || ln -sv gtksourceview-3.0 ${path}

_echot "------- user conf"
paths=".tmux"
for path in ${paths}; do
	_keepmv ${path}
done
for file in ${_PATH_BASE}/conf/user.tmux.tar.gz; do
	tar xzf ${file} -C ${HOME}/
done

_echot "------- tmux desktop"
_eval cp ${_PATH_BASE}/xtra/xfce4-terminal-tmux.desktop ${HOME}/.local/share/applications/

_echot "------- nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap " # various
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor" # color
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------- language-specs conf"
_evalr cp ${_PATH_BASE}/conf/gtk/*.lang /usr/share/gtksourceview-3.0/language-specs/

_echot "------- aegisub"
path=${HOME}/.aegisub/
[ -d "${path}" ] || mkdir -p ${path}
_eval cp ${_PATH_BASE}/conf/aegisub-config.json ${path}

#_echot "------- dvd"
#sudo dpkg-reconfigure libdvd-pkg

_echot "------- QT5"
_echoA "After validation, adjust settings for qt5 and close qt5ct window"
_askno "Validate to continue"
qt5ct 2>/dev/null

_echot "------- plank"
path=${HOME}/.config/autostart
[ -d "${path}" ] || mkdir -p ${path}
cp ${_PATH_BASE}/xtra/plank.desktop ${path}/
_echoA "After validation, adjust plank preferences and close plank window"
_askno "Validate to continue"
plank --preferences &
