#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

grep -q "^# ${_PART}" "${_FILE_CONF}" || echo -e "# ${_PART}" >> "${_FILE_CONF}"

########################  MAIN

_echot "------------------ reduce swapiness"
echo "vm.swappiness=40" |sudo tee -a /etc/sysctl.d/99-swappiness.conf

_echot "------------------ grub"
file=/etc/default/grub
_keepcp ${file}
sudo sed -i "s|^.\?\(GRUB_TIMEOUT_STYLE\)=.*|\1=menu|" ${file}
sudo sed -i "/^GRUB_TIMEOUT=/ s|=.*|=2|" ${file}
sudo sed -i "/^GRUB_DEFAULT=/ s|=.*|=0|" ${file}
sudo sed -i "/^GRUB_SAVEDEFAULT=/ s|=.*|=false|" ${file} # manjaro
file=/etc/grub.d/00_header
_keepcp ${file}
sudo sed -i "s|30|2|g" ${file}
_evalr update-grub

_echot "------------------ grub os-prober"
# add identifier to menuentry
file=/etc/grub.d/30_os-prober
if ! grep -q 'LONGNAME="${LONGNAME} ${BTRFSsubvol/#subvol=/}"' ${file}; then
	_keepcp ${file} && sudo chmod -x ${file}.keep
	sudo sed -i "/LONGNAME=\"\${LABEL}\"/ a\  else\n    LONGNAME=\"\${LONGNAME} \${BTRFSsubvol/#subvol=/}\"" ${file}
fi

_echot "------------------ numlockx in tty"
file=/etc/lightdm/lightdm-gtk-greeter.conf
# ally-states
if grep -q "^a11y-states *=" ${file}; then
	sudo sed -i "s|\(^a11y-states.*\)$|\1;+keyboard|" ${file}
else
	sudo sh -c "echo 'a11y-states = +keyboard' >> ${file}"
fi

_echot "------------------ numlockx in ldm"
file=/etc/lightdm/lightdm-gtk-greeter.conf
cmd="/usr/bin/numlockx on"
# keyboard
if grep -q "^keyboard *=" ${file}; then
	sudo sed -i "s|\(^keyboard *=\)|\1 ${cmd}|" ${file}
else
	sudo sh -c "echo 'keyboard = ${cmd}' >> ${file}"
fi

_echot "------------------  bash-completion"
_evalr "cp -a ${_PATH_BASE}/xtra/bash-completion/* /usr/share/bash-completion/completions/"

_echot "------------------  icons"
path=${HOME}/.local/share/icons
cp ${_PATH_BASE}/icons/* ${path}/
path=/usr/share/icons/Foralyse
[ -d "${path}" ] || sudo mkdir -p ${path}
sudo cp ${_PATH_BASE}/icons/* ${path}/

_echot "------------------  vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------------------ vim colors"
sudo cp ${_PATH_BASE}/conf/vim/* /usr/share/vim/vim*/colors/

_echot "----------  vim conf"
file=/etc/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------------------  /usr/local/bs/conf links"
for file in .nanorc .tmux.conf .vimrc; do
	path_from="${_PATH_BS}/conf/${file}"
	path=${HOME}/${file}
	_keepmv "${path}"
	ln -s "${path_from}" "${path}"
done

_echot "------------------ tmux"
tar xzf ${_PATH_BASE}/conf/user.tmux.tar.gz -C ${HOME}/
_eval cp ${_PATH_BASE}/xtra/org.gnome.Terminal-tmux.desktop ${HOME}/.local/share/applications/

_echot "------------------ nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap " # various
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor" # color
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------------------  profile"
sudo sh -c "echo '
#  PATH
export PATH=${PATH}:${_PATH_BS}
# QT
export QT_QPA_PLATFORMTHEME=qt5ct' >> /etc/profile.d/desktop.sh"

_echot "------------------ meld style"
_evalr cp ${_PATH_BASE}/conf/meld-dark.xml /usr/share/meld/styles/meld-dark.xml

_echot "------------------ language-specs conf"
_evalr cp ${_PATH_BASE}/conf/gtk/*.lang /usr/share/gtksourceview-3.0/language-specs/

_echot "------------------ aegisub"
path=${HOME}/.aegisub/
[ -d "${path}" ] || mkdir -p ${path}
_eval cp ${_PATH_BASE}/conf/aegisub-config.json ${path}

#_echot "------------------ dvd"
#sudo dpkg-reconfigure libdvd-pkg

_echot "------------------ gtk styles"
path=${HOME}/.local/share/gtksourceview-3.0
[ -d "${path}" ] || mkdir -p ${path}
path=${HOME}/.local/share/gtksourceview-3.0/styles
# link or copy
path_repo=/home/shared/.local/share/gtksourceview-3.0/styles
if [ -d "${path_repo}" ]; then
	[ -d "${path}" ] && rm -fR ${path}
	ln -sv "${path_repo}" ${path}
else
	[ -d "${path}" ] || mkdir -p ${path}
	_eval cp ${_PATH_BASE}/conf/styles/* ${path}/
fi
# gtk 4
cd ${HOME}/.local/share
path=gtksourceview-4
[ -e "${path}" ] || ln -sv gtksourceview-3.0 ${path}

_echot "------------------ firefox tweaks"
path=${HOME}/.mozilla/firefox/${USER}
if [ -d "${path}" ]; then
	ln -sv "${_PATH_BASE}/conf/user.js" ${path}
	chown ${USER}:${USER} ${path}
fi

_echot "------------------ wp"
_evalr cp -a ${_PATH_BASE}/xtra/wp/* /usr/share/backgrounds/xfce/
_evalr chmod 644 /usr/share/backgrounds/xfce/*

########################  END

_echoT "===================== ${_PART} end"
_partadd ${_PART} ${_FILE_DONE}


# _echot "------------------ numlock tty service"
# file=/usr/local/bin/numlock
# echo '#!/bin/bash
# for tty in /dev/tty{1..6}
# do
# 	/usr/bin/setleds -D +num < "$tty";
# done' | sudo tee ${file}
# sudo chmod +x ${file}

# file_service=/etc/systemd/system/numlock.service
# sudo sh -c "echo '[Unit]
# Description=numlock

# [Service]
# ExecStart=${file}
# StandardInput=tty
# RemainAfterExit=yes

# [Install]
# WantedBy=multi-user.target' > ${file_service}"
# _service enable numlock
