#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

########################  MAIN

_echot "-------  upgrade"
_eval upgrade

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_ask "Valid to reboot"
sudo reboot
