#!/bin/bash

_echot "------- install"
packages="freecad"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
    || { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- aur"
packages="freecad-a2plus-git freecad-fcgear-git freecad-cadquery-git"
_install_aur ${packages}
