#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

########################  MAIN

_echot "------------------  system"
packages="bash-completion cdrtools curl exfatprogs gnupg gparted htop most multipath-tools pv testdisk tmux tree yay"
packages+=" gzip p7zip zip unzip unrar"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ tools"
packages="baobab dconf-editor gtk2fontsel meld qt5ct thunderbird termdown"
packages+=" jre-openjdk"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ libreoffice"
packages="libreoffice-still"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ media"
packages=" audacity cheese easytag pulseaudio-equalizer simplescreenrecorder soundconverter sound-juicer yt-dlp"
packages+=" gimp gimp-nufraw gimp-plugin-gmic inkscape"
packages+=" handbrake libdvdcss libdvdnav libdvdread mkvtoolnix-gui mpv"
packages+=" aegisub boost-libs"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
