#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- system"
packages="base-devel bash-completion cdrtools curl exfatprogs gnupg gparted htop most multipath-tools numlockx pv testdisk tmux tree yay"
packages+=" gzip p7zip zip unzip unrar"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- tools"
packages="baobab dconf-editor gtk2fontsel meld qt5ct thunderbird termdown"
packages+=" jre-openjdk"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- libreoffice"
packages="libreoffice-still"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- graphic"
packages="inkscape gimp"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- audio"
packages="audacity easytag pulseaudio-equalizer soundconverter sound-juicer yt-dlp"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- video"
packages="cheese handbrake kdenlive libdvdcss libdvdnav libdvdread mkvtoolnix-gui mpv simplescreenrecorder"
packages+=" aegisub boost-libs"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- aur"
packages="gmusicbrowser qarte"
# webcamoid
packages+=" radiotray-ng zuki-themes"
for package in ${packages}; do
	if ! yay -Qe ${package} >/dev/null 2>&1; then
		_echot "install ${package}"
		${_CMD_AUR} ${package} || _exite "Unable to install: ${package}"
	else
		_echot "already installed ${package}"
	fi
done
