#!/bin/bash

_echot "------- install"
packages="inkscape gimp gimp-plugin-gmic"
packages+=" darktable krita"
# darkroom shotwell gimp-nufraw
_install_pcks ${packages}

_echot "------- aur"
packages="gimp-fourier gimp-paint-studio gimp-plugin-pandora"
# too big: gimp-plugin-resynthesizer-git
# not available: gimp-plugin-saveforweb
# wait for good version:  gimp-extras gimp-plugin-bimp gimp-plugin-beautify
# wait for good version:  gimp-plugin-texturize gimp-plugin-refocusit
_install_aur ${packages}
