#!/bin/bash

_echot "------- install"
packages="inkscape gimp gimp-nufraw gimp-plugin-gmic"
packages+=" darktable krita"
# darkroom shotwell
_install_pcks ${packages}

_echot "------- aur"
packages="gimp-extras gimp-fourier gimp-paint-studio gimp-plugin-bimp gimp-plugin-pandora gimp-plugin-refocusit gimp-plugin-saveforweb"
# too big: gimp-plugin-resynthesizer-git
# wait for good version:  gimp-plugin-beautify gimp-plugin-texturize
_install_aur ${packages}
