#!/bin/bash

_echot "------- tlp"
packages="tlp tlp-rdw tlpui" # acpi
_install_pcks ${packages}

_echot "------- tlp"
_service enable tlp

_echot "------- enable acpid"
service=acpid
_service enable ${service}
_service start ${service}

_echot "------- show battery percentage"
_eval "gsettings set org.gnome.desktop.interface show-battery-percentage true"

_echot "------- no beep"
#echo "blacklist pcspkr" | sudo tee -a /etc/modprobe.d/nobeep.conf
echo 'xset -b' >> ~/.xprofile

# try it if standard acpi failed
#str=" acpi_backlight=vendor" # just try
#str+=" fbcon=nodefer" # just try
#if [ "${str}" ] && ! grep -q '^GRUB_CMDLINE_LINUX=.*${str}' ${file}; then
#	 sudo sed -i "/^GRUB_CMDLINE_LINUX=/ s|\"$|${str}\"|" ${file}
#fi
