#!/bin/bash

_echoa "This part is to use shared path in GUEST"
_echoe "Do not use this part in HOST"
_askyn "Types 'y' to continue or anything else to exit"
[ "${_ANSWER}" != "y" ] && _exit

########################  REQUIRE

_echot "------- required files"
file_script_nbd=${_PATH_BASE}/bs/scripts/nbd.sh
file_conf_ca=${_PATH_BASE}/conf/ca.xml

_require ${file_script_nbd} ${file_conf_ca}

########################  CHECK

_echoA "Read the following lines and confirm the virtualzation is activated from BIOS"
_eval LC_ALL=C lscpu | grep -i virtual
_askyn "Confirm by typing 'y'"
[ "${_ANSWER}" != "n" ] && _exit

########################  DATA

if [ -z "${_PATH_VIRT}" ]; then
	anstmp=/vms/virt
	_askno "Give the path for virt (${anstmp})"
	_PATH_VIRT=${_ANSWER:-${anstmp}}
	_confset _PATH_VIRT "${_PATH_VIRT}"
fi

f [ -z "${_PATH_SHARE}" ]; then
	anstmp=/vms/share
	_askno "Give the shared path from the Host (${anstmp})"
	_PATH_SHARE=${_ANSWER:-${anstmp}}
	_confset _PATH_SHARE "${_PATH_SHARE}"
fi

if [ -z "${_PATH_NBD}" ]; then
	anstmp=/vms/nbd
	_askno "Give the path to mount device files (${anstmp})"
	_PATH_NBD=${_ANSWER:-$anstmp}
	_confset _PATH_NBD "${_PATH_NBD}"
fi

########################  MAIN

_echot "------- install"
packages="edk2-ovmf libvirt qemu-desktop virt-manager virt-viewer"
packages+=" bridge-utils dnsmasq iptables-nft libguestfs"
# packages+="  openbsd-netcat vde2 "
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- tpm support"
packages="--asdeps swtpm"
# virtualbox-guest-iso
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- service"
_service enable libvirtd

########################  CONF

_echot "------- ${_PATH_VIRT}"
pth="${_PATH_VIRT}"
[ -d "${pth}" ] || _evalr mkdir -p ${pth}
_evalr chown libvirt-qemu:libvirt-qemu ${pth}

_echot "------- ${USER} in libvirt,libvirt-qemu,kvm"
_evalr usermod -aG libvirt, libvirt-qemu, kvm ${USER}

########################  ISO

_echot "------- /vms/iso"
pth=/vms/iso
[ -d "${pth}" ] || _evalr mkdir -p "${pth}"
_evalr chown ${USER}:${USER} ${pth}
# to give group write modifications for mkisofs and virt-manager
_evalr setfacl -dm o::rx,g::rwx,o::r ${pth}

########################  SHARE

_echot "------- ${_PATH_SHARE}"
pth="${_PATH_SHARE}"
[ -d "${pth}" ] || _evalr mkdir -p "${pth}"
_evalr chown ${USER}:${USER} ${_PATH_SHARE}
_evalr setfacl -Rm u:libvirt-qemu:rwx ${_PATH_SHARE}
_evalr setfacl -d -Rm u:libvirt-qemu:rwx ${_PATH_SHARE}
_evalr setfacl -Rm g:libvirt-qemu:rwx ${_PATH_SHARE}
_evalr setfacl -d -Rm g:libvirt-qemu:rwx ${_PATH_SHARE}

_echoA "Configure your guest in virt-manager to share path with this parameters: "
echo "Source path: ${_PATH_SHARE}"
echo "Target path: /hostshare"
_echoA "\nAnd add fmode and dmode by modifying XML settings options in virt-manager:"
echo -e 'filesystem type="mount" accessmode="mapped" '${blue}'fmode="0664" dmode="0775"'${cclear}'>
  <source dir="/vms/share"/>
  <target dir="/hostshare"/>
  <address type="pci" domain="0x0000" bus="0x07" slot="0x00" function="0x0"/>
</filesystem>'

########################  NBD

_echot "------- ${_PATH_NBD}"
pth="${_PATH_NBD}"
[ -d "${pth}" ] || _evalr mkdir -p ${pth}
_evalr chown ${USER}:${USER} ${pth}

_echot "------- install"
packages="qemu-img"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- script"
file=/usr/local/bin/nbd
_evalr cp ${file_script_nbd} ${file}
_evalr chmod +x ${file}
sudo sed -i "/^_PATH_NBD=/ s|=.*$|=\"${_PATH_NBD}\"|" ${file}

_echot "------- bookmarks"
file=${HOME}/.config/gtk-3.0/bookmarks
grep -q "file://${_PATH_NBD}" ${file} || echo "file://${_PATH_NBD}" >> ${file}

_echot "------- CA"
file=~/.config/Thunar/uca.xml
[ -d ~/.config/Thunar ] || mkdir -p ~/.config/Thunar
if [ -f "${file}" ]; then
	_keepcpts ${file}
else
	echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<actions>\n</actions>' > ${file}
fi
# not already made
if ! grep -q 1655620394868230-1 ${file}; then
	sed -i '$,1d' ${file}
	cat ${file} ${file_conf_ca} > ${file}.tmp
	_eval mv ${file}.tmp ${file}
fi

########################  REBOOT

_echot "------- soft-reboot"
_echoA "Be careful, close others softwares the system will soft-reboot"
_echoA "This session will be closed"
_askno "Validate to continue"
_evalr systemctl soft-reboot 
