#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- update"
${_CMD} -Sy

_echot "------- upgrade"
${_CMD} -Su

_echot "------- clean orphans"
${_CMD} -R $(pacman -Qdtq)

########################  END

_partadd "${_PART}" "${_FILE_DONE}"
