#!/bin/bash
#
# write by Aguy

########################  MAIN

_echoT "\n==========================================  ${_PART}"

_echot "------------------ update"
${_CMD} -Sy

_echot "------------------ upgrade"
${_CMD} -Su

_echot "------------------ clean orphans"
${_CMD} -R $(pacman -Qdtq)

_echot "------------------ clear cache"
${_CMD} -Sc

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
